# Unique name for this workflow
name: Package Build

# Definition when the workflow should run
on:
  workflow_dispatch:
  push:
    branches:
      - main
# Jobs to be executed
jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    container: dxatscale/sfpowerscripts
    steps:
      # Checkout the code
      - name: "Checkout source code"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Copy Auth URL to file
      - name: "Copy Auth URL to file"
        shell: bash
        run: |
          echo "${{ secrets.DEVHUB_AUTH_URL }}" > ./AUTH_URL
      # Authenticate dev hub
      - name: "Authenicate Org"
        run: "sfdx auth:sfdxurl:store -f ./AUTH_URL -a devhub"
      # Create Package
      - name: "Create package"
        run: |
          packageId=$( sfdx force:package:version:create -c -d pkg/ -f config/project-scratch-def.json -x -v devhub -w 300 --json | jq .result.SubscriberPackageVersionId )
          echo "PACKAGE_ID=${packageId}" >> $GITHUB_ENV
      # Get test results
      - name: "Fetch Test Results"
        run: |
          testCoverage=$( sfdx force:package:version:report -p ${{ env.PACKAGE_ID }} -v devhub --json | jq .result.CodeCoverage.apexCodeCoveragePercentage )
          echo "TEST_COVERAGE=${testCoverage}" >> $GITHUB_ENV
      # Publish tests
      - name: Publish Test Results
        uses: schneegans/dynamic-badges-action@v1.1.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: ${{ secrets.GIST_ID }}
          filename: feature-management-test.json
          label: Code Coverage
          message: ${{ env.TEST_COVERAGE }}%
          color: green
          namedLogo: "Salesforce"
          isError: ${{ env.TEST_COVERAGE < 75}}
