# Unique name for this workflow
name: PMD Validation

# Definition when the workflow should run
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]

# Jobs to be executed
jobs:
  static-code-analysis:
    name: Review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Install Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      -name: PMD Validation
        uses: pmd/pmd-github-action@v1
        with:
          rulesets: "./pmd-ruleset.xml"
          analyzeModifiedFilesOnly: true
      - name: Create Review from PMD report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: pmd-report.sarif
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
